spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        file-extension: yaml

springfox:
  documentation:
    enabled: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: order_order